name: Pipeline CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v2

      - name: Listar arquivos no diretório
        run: |
          echo "Estrutura do diretório:"
          ls -alh

      - name: Configurar o Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalar dependências e rodar os testes
        run: |
          npm install
          npm test

  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v2

      - name: Instalar OWASP ZAP usando Snap
        run: |
          sudo apt update
          sudo apt install -y snapd
          sudo snap install zaproxy --classic

      - name: Rodar escaneamento de segurança com OWASP ZAP
        run: |
          zaproxy -cmd -quickurl http://localhost:3000 -quickout report.html
      - name: Fazer upload do relatório do OWASP ZAP
        uses: actions/upload-artifact@v3
        with:
          name: relatorio-owasp-zap
          path: report.html

  deploy:
    runs-on: ubuntu-latest
    needs: [build, security_scan]

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v2

      - name: Logue no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir e enviar a imagem Docker
        run: |
          docker build -t amoracamila12/lacrei-saude-api:latest .
          docker push amoracamila12/lacrei-saude-api:latest
